/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CatalogoRouteImport } from './routes/catalogo'
import { Route as CarrinhoRouteImport } from './routes/carrinho'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProdutoSlugRouteImport } from './routes/produto.$slug'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedAdminProdutosRouteImport } from './routes/_authenticated/admin/produtos'
import { Route as AuthenticatedAdminPedidosRouteImport } from './routes/_authenticated/admin/pedidos'
import { Route as AuthenticatedAdminCuponsRouteImport } from './routes/_authenticated/admin/cupons'
import { Route as AuthenticatedAdminCategoriasRouteImport } from './routes/_authenticated/admin/categorias'

const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogoRoute = CatalogoRouteImport.update({
  id: '/catalogo',
  path: '/catalogo',
  getParentRoute: () => rootRouteImport,
} as any)
const CarrinhoRoute = CarrinhoRouteImport.update({
  id: '/carrinho',
  path: '/carrinho',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutoSlugRoute = ProdutoSlugRouteImport.update({
  id: '/produto/$slug',
  path: '/produto/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminProdutosRoute =
  AuthenticatedAdminProdutosRouteImport.update({
    id: '/produtos',
    path: '/produtos',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminPedidosRoute =
  AuthenticatedAdminPedidosRouteImport.update({
    id: '/pedidos',
    path: '/pedidos',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminCuponsRoute =
  AuthenticatedAdminCuponsRouteImport.update({
    id: '/cupons',
    path: '/cupons',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminCategoriasRoute =
  AuthenticatedAdminCategoriasRouteImport.update({
    id: '/categorias',
    path: '/categorias',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/carrinho': typeof CarrinhoRoute
  '/catalogo': typeof CatalogoRoute
  '/checkout': typeof CheckoutRoute
  '/contato': typeof ContatoRoute
  '/sobre': typeof SobreRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/produto/$slug': typeof ProdutoSlugRoute
  '/admin/categorias': typeof AuthenticatedAdminCategoriasRoute
  '/admin/cupons': typeof AuthenticatedAdminCuponsRoute
  '/admin/pedidos': typeof AuthenticatedAdminPedidosRoute
  '/admin/produtos': typeof AuthenticatedAdminProdutosRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/carrinho': typeof CarrinhoRoute
  '/catalogo': typeof CatalogoRoute
  '/checkout': typeof CheckoutRoute
  '/contato': typeof ContatoRoute
  '/sobre': typeof SobreRoute
  '/produto/$slug': typeof ProdutoSlugRoute
  '/admin/categorias': typeof AuthenticatedAdminCategoriasRoute
  '/admin/cupons': typeof AuthenticatedAdminCuponsRoute
  '/admin/pedidos': typeof AuthenticatedAdminPedidosRoute
  '/admin/produtos': typeof AuthenticatedAdminProdutosRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/carrinho': typeof CarrinhoRoute
  '/catalogo': typeof CatalogoRoute
  '/checkout': typeof CheckoutRoute
  '/contato': typeof ContatoRoute
  '/sobre': typeof SobreRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/produto/$slug': typeof ProdutoSlugRoute
  '/_authenticated/admin/categorias': typeof AuthenticatedAdminCategoriasRoute
  '/_authenticated/admin/cupons': typeof AuthenticatedAdminCuponsRoute
  '/_authenticated/admin/pedidos': typeof AuthenticatedAdminPedidosRoute
  '/_authenticated/admin/produtos': typeof AuthenticatedAdminProdutosRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/carrinho'
    | '/catalogo'
    | '/checkout'
    | '/contato'
    | '/sobre'
    | '/admin'
    | '/produto/$slug'
    | '/admin/categorias'
    | '/admin/cupons'
    | '/admin/pedidos'
    | '/admin/produtos'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/carrinho'
    | '/catalogo'
    | '/checkout'
    | '/contato'
    | '/sobre'
    | '/produto/$slug'
    | '/admin/categorias'
    | '/admin/cupons'
    | '/admin/pedidos'
    | '/admin/produtos'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/carrinho'
    | '/catalogo'
    | '/checkout'
    | '/contato'
    | '/sobre'
    | '/_authenticated/admin'
    | '/produto/$slug'
    | '/_authenticated/admin/categorias'
    | '/_authenticated/admin/cupons'
    | '/_authenticated/admin/pedidos'
    | '/_authenticated/admin/produtos'
    | '/_authenticated/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  CarrinhoRoute: typeof CarrinhoRoute
  CatalogoRoute: typeof CatalogoRoute
  CheckoutRoute: typeof CheckoutRoute
  ContatoRoute: typeof ContatoRoute
  SobreRoute: typeof SobreRoute
  ProdutoSlugRoute: typeof ProdutoSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalogo': {
      id: '/catalogo'
      path: '/catalogo'
      fullPath: '/catalogo'
      preLoaderRoute: typeof CatalogoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carrinho': {
      id: '/carrinho'
      path: '/carrinho'
      fullPath: '/carrinho'
      preLoaderRoute: typeof CarrinhoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produto/$slug': {
      id: '/produto/$slug'
      path: '/produto/$slug'
      fullPath: '/produto/$slug'
      preLoaderRoute: typeof ProdutoSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/produtos': {
      id: '/_authenticated/admin/produtos'
      path: '/produtos'
      fullPath: '/admin/produtos'
      preLoaderRoute: typeof AuthenticatedAdminProdutosRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/pedidos': {
      id: '/_authenticated/admin/pedidos'
      path: '/pedidos'
      fullPath: '/admin/pedidos'
      preLoaderRoute: typeof AuthenticatedAdminPedidosRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/cupons': {
      id: '/_authenticated/admin/cupons'
      path: '/cupons'
      fullPath: '/admin/cupons'
      preLoaderRoute: typeof AuthenticatedAdminCuponsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/categorias': {
      id: '/_authenticated/admin/categorias'
      path: '/categorias'
      fullPath: '/admin/categorias'
      preLoaderRoute: typeof AuthenticatedAdminCategoriasRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
  }
}

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminCategoriasRoute: typeof AuthenticatedAdminCategoriasRoute
  AuthenticatedAdminCuponsRoute: typeof AuthenticatedAdminCuponsRoute
  AuthenticatedAdminPedidosRoute: typeof AuthenticatedAdminPedidosRoute
  AuthenticatedAdminProdutosRoute: typeof AuthenticatedAdminProdutosRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminCategoriasRoute: AuthenticatedAdminCategoriasRoute,
    AuthenticatedAdminCuponsRoute: AuthenticatedAdminCuponsRoute,
    AuthenticatedAdminPedidosRoute: AuthenticatedAdminPedidosRoute,
    AuthenticatedAdminProdutosRoute: AuthenticatedAdminProdutosRoute,
    AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  CarrinhoRoute: CarrinhoRoute,
  CatalogoRoute: CatalogoRoute,
  CheckoutRoute: CheckoutRoute,
  ContatoRoute: ContatoRoute,
  SobreRoute: SobreRoute,
  ProdutoSlugRoute: ProdutoSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
